web:
  driver_arguments:
    # The arguments to pass to the webdriver. E.g.: add --headless to run in headless mode
    - --no-sandbox
    - --disable-dev-shm-usage
  urls:
    # base_url: The URL to start crawling with
    # prefix: Only crawl URLs matching the specified prefix
    # depth: The maximum depth for BFS traversal
    # You can add more websites by adding more entries (don't forget the - prefix from YAML)
    - base_url: https://medium.com/
      prefix: https://medium.com/
      depth: 1
    - base_url: https://www.freecodecamp.org/
      prefix: https://www.freecodecamp.org/
      depth: 1
